# docker-compose.yml
version: '3.8'
services:
  api-ats-works-clean-architecture:
    build: .
    ports:
      - "3001:3001"
    networks:
      - pgvector_default

networks:
  pgvector_default:
    external: true